# Reusable vars
x-var:
  - &POSTGRES_USER postgres
  - &POSTGRES_PASSWORD default
  - &POSTGRES_DATABASE postgres
  - &node-image node:22

# Postgres envars
x-postgres-vars: &postgres-vars
  POSTGRES_DATABASE: postgres
  POSTGRES_HOST: db
  POSTGRES_PASSWORD: default
  POSTGRES_USER: *POSTGRES_USER

name: Capstone-2026
services:
  # DB
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    # Don't put an image: prop here, it breaks the local
    container_name: database
    environment:
      <<: *postgres-vars
    ports: [5432:5432]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", *POSTGRES_USER]
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # PGAdmin
  pgadmin:
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@qs.com
      PGADMIN_DEFAULT_PASSWORD: admin
    image: dpage/pgadmin4
    ports: [5050:80]
    profiles: ["pgadmin"]

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      database:
        condition: service_healthy
    develop:
     watch:
       - action: sync
         path: ./backend/
         target: /app
         ignore: [node_modules]
    environment:
      LOG_LEVEL: info
      PORT: 3000
      <<: *postgres-vars
      DATABASE_URL: ${DATABASE_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports: ["3000:3000"]
    volumes: ["./backend:/app", "/app/node_modules/", "/app/dist/"]
    # For debugging
    stdin_open: true
    tty: true

  # Frontend
  frontend:
    container_name: frontend
    image: node:20.19.2
    working_dir: /app/frontend
    command: sh -c "npm ci && npm run dev -- --host"
    depends_on:
      backend:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore: [node_modules]
    environment:
      VITE_BACKEND_URL: http://localhost:3000
    healthcheck:
      test: curl --fail http://localhost:5173 || exit 1
    ports: ["5173:5173"]
    # entrypoint: ls /app
    volumes:
      - ./frontend:/app
      - /app/node_modules

  caddy:
    container_name: caddy
    profiles: ["caddy"]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 5173
      VITE_BACKEND_URL: http://localhost:3000
      LOG_LEVEL: info
    ports: ["5173:5173"]
    volumes: ["./frontend/Caddyfile:/etc/caddy/Caddyfile"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_data: